/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import javax.swing.JOptionPane;
import negocio.Cliente;
import persistencia.ControlaCliente;


/**
 *
 * @author jasom
 */
public class CadastroClientes extends javax.swing.JFrame {
     
     private ControlaCliente cc = new ControlaCliente();
     
     
     
     public CadastroClientes() {
        initComponents();
    }

      public CadastroClientes(ControlaCliente cc) {
          this.cc = cc;
          initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfdNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfdTelefone = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnVerTodos = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfdSobrenome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfdTreinamento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfdEndereco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfdRazaoSocial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdDescricao = new javax.swing.JTextField();
        btnSave1 = new javax.swing.JButton();
        btnVerTodos1 = new javax.swing.JButton();
        btnSair1 = new javax.swing.JButton();
        btnSalvar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfdNomeFantasia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfdCnpj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfdAtividade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Sistema de Cadastro de Instrutores");

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnVerTodos.setText("Ver todos");
        btnVerTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodosActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setText("Adicionar na tabela");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel3.setText("Sobrenome:");

        jLabel4.setText("Treinamento:");

        tfdTreinamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdTreinamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Telefone:");

        jLabel5.setText("Endereço:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clientes - Cadastro/Consulta ");
        setBackground(new java.awt.Color(0, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Cadastre um novo Cliente ");

        btnSave1.setText("Salvar");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        btnVerTodos1.setText("Ver todos");
        btnVerTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTodos1ActionPerformed(evt);
            }
        });

        btnSair1.setText("Sair");
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });

        btnSalvar1.setText("Adicionar na tabela");
        btnSalvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvar1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nome Fantasia:");

        jLabel9.setText("CNPJ:");

        tfdCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdCnpjActionPerformed(evt);
            }
        });

        jLabel10.setText("Razao Social:");

        jLabel11.setText("Descrição:");

        jLabel12.setText("Atividade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(tfdRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(tfdNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(69, 69, 69)
                        .addComponent(tfdCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(47, 47, 47)
                        .addComponent(tfdAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSalvar1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(46, 46, 46)
                            .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnVerTodos1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tfdRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(tfdNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9))
                    .addComponent(tfdCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(tfdAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tfdDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSalvar1)
                .addGap(18, 18, 18)
                .addComponent(btnVerTodos1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair1)
                    .addComponent(btnSave1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String path = "c:\\temp\\instrutores.csv";
        if(cc.salvarEmArquivo(path)){
            JOptionPane.showMessageDialog(null, "Instrutores cadastrados com sucesso!\nArquivo atualizado.");
            tfdNome.setText("");
            tfdSobrenome.setText("");
            tfdTreinamento.setText("");
            tfdEndereco.setText("");
            tfdTelefone.setText("");
            tfdNome.requestFocus();
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro ao atualizar o Arquivo!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnVerTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodosActionPerformed
        DlgMostraClientes dlg = new DlgMostraClientes(null, true, cc);
        dlg.setVisible(true);
    }//GEN-LAST:event_btnVerTodosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int resposta =   JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        switch (resposta) {
            case JOptionPane.YES_OPTION:
            this.dispose();
            case JOptionPane.NO_OPTION:

            break;
            case JOptionPane.CLOSED_OPTION:

            break;
            default:
            break;
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Cliente cliente = new Cliente(); //instaciamos o obej instrutor para populalo com as informacoes dos campos de texto

        cliente.setRazaoSocial(tfdRazaoSocial.getText());
        cliente.setNomeFantasia(tfdNomeFantasia.getText());
        cliente.setCnpj(tfdCnpj.getText());
        cliente.setAtividade(tfdAtividade.getText());
        cliente.setDescrição(tfdDescricao.getText());

        //tentar salvar
        if(cc.salvar(cliente)){
            JOptionPane.showMessageDialog(null, "Cliente adicionado à tabela.\nAntes de sair clique em salvar.");
            tfdRazaoSocial.setText("");
            tfdNomeFantasia.setText("");
            tfdCnpj.setText("");
            tfdAtividade.setText("");
            tfdDescricao.setText("");
            tfdRazaoSocial.requestFocus();
        }

        else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Cliente!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void tfdTreinamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdTreinamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdTreinamentoActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        String pathC = "c:\\temp\\clientes.csv";
        
        if(cc.salvarEmArquivo(pathC)){
            JOptionPane.showMessageDialog(null, "clientes cadastrados com sucesso!\nArquivo atualizado.");
            tfdRazaoSocial.setText("");
            tfdNomeFantasia.setText("");
            tfdCnpj.setText("");
            tfdAtividade.setText("");
            tfdDescricao.setText("");
            tfdRazaoSocial.requestFocus();
        }
        else{
            JOptionPane.showMessageDialog(null, "Erro ao atualizar o Arquivo!");
        }
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnVerTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTodos1ActionPerformed
        DlgMostraClientes dlg = new DlgMostraClientes(null, true, cc);
        dlg.setVisible(true);
        dlg.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVerTodos1ActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        int resposta =   JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        switch (resposta) {
            case JOptionPane.YES_OPTION:
            this.dispose();
            case JOptionPane.NO_OPTION:

            break;
            case JOptionPane.CLOSED_OPTION:

            break;
            default:
            break;
        }
    }//GEN-LAST:event_btnSair1ActionPerformed

    private void btnSalvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvar1ActionPerformed
        Cliente cliente = new Cliente(); //instaciamos o obej instrutor para populalo com as informacoes dos campos de texto

        cliente.setRazaoSocial(tfdRazaoSocial.getText());
        cliente.setNomeFantasia(tfdNomeFantasia.getText());
        cliente.setCnpj(tfdCnpj.getText());
        cliente.setAtividade(tfdAtividade.getText());
        cliente.setDescrição(tfdDescricao.getText());

        //tentar salvar
        if(cc.salvar(cliente)){
            JOptionPane.showMessageDialog(null, "Cliente adicionado à tabela.\nAntes de sair clique em salvar.");
            tfdRazaoSocial.setText("");
            tfdNomeFantasia.setText("");
            tfdCnpj.setText("");
            tfdAtividade.setText("");
            tfdDescricao.setText("");
            tfdRazaoSocial.requestFocus();
        }

        else{
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar Cliente!");
        }
    }//GEN-LAST:event_btnSalvar1ActionPerformed

    private void tfdCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdCnpjActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSalvar1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnVerTodos;
    private javax.swing.JButton btnVerTodos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tfdAtividade;
    private javax.swing.JTextField tfdCnpj;
    private javax.swing.JTextField tfdDescricao;
    private javax.swing.JTextField tfdEndereco;
    private javax.swing.JTextField tfdNome;
    private javax.swing.JTextField tfdNomeFantasia;
    private javax.swing.JTextField tfdRazaoSocial;
    private javax.swing.JTextField tfdSobrenome;
    private javax.swing.JTextField tfdTelefone;
    private javax.swing.JTextField tfdTreinamento;
    // End of variables declaration//GEN-END:variables
}
